name: test

on:
  push:
    branches-ignore:
      - "development/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-concurrency 1

      - name: Run linter
        run: yarn lint

      - name: Build typescript
        run: yarn build
